id: opecha:P010684
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG16554
  title: དགེ་འདུན་ཆོས་འཕེལ་དང་ཆབ་སྤེལ་ཚེ་བརྟན་ཕུན་ཚོགས་ཀྱི་རིག་གཞུང་བསམ་བློ་སྐོར་གྱི་བགྲོ་གླེང་ཚོགས་འདུའི་དཔྱད་རྩོམ་ལེགས་བཏུས།
  volume: ''
  author: ''
