id: P010684
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-20 10:19:46.731692
source_metadata:
  id: bdr:W1KG16554
  title: དགེ་འདུན་ཆོས་འཕེལ་དང་ཆབ་སྤེལ་ཚེ་བརྟན་ཕུན་ཚོགས་ཀྱི་རིག་གཞུང་བསམ་བློ་སྐོར་གྱི་བགྲོ་གླེང་ཚོགས་འདུའི་དཔྱད་རྩོམ་ལེགས་བཏུས།
  author: ''
  volumes:
    c37d8f2bea2e4fc1abb573351735fed4:
      image_group_id: I2PD18657
      title: ''
      volume_number: 1
      total_pages: 408
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
