id: I9A131A4C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T06:58:17+00:00'
last_modified: '2022-06-08T16:47:18.877893+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG16554
  title: དགེ་འདུན་ཆོས་འཕེལ་དང་ཆབ་སྤེལ་ཚེ་བརྟན་ཕུན་ཚོགས་ཀྱི་རིག་གཞུང་བསམ་བློ་སྐོར་གྱི་བགྲོ་གླེང་ཚོགས་འདུའི་དཔྱད་རྩོམ་ལེགས་བཏུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    D3CD:
      image_group_id: I2PD18657
      title: ''
      total_pages: 408
      order: 1
      base_file: D3CD.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
